name: tests

on:
  push:
  schedule:
    - cron:  '0 2 * * *'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install toolchain
      uses: ada-actions/toolchain@ce2021
      with:
        distrib: community
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python python3-dev python3-setuptools
        pip3 install gcovr
    - name: Cache Z3
      uses: actions/cache@v2
      with:
          path: |
              z3/z3/build/libz3.so
              z3/z3/build/Makefile
          key: ${{ hashFiles('z3/z3/CMakeLists.txt', 'Makefile') }}
    - name: Test
      run: |
        make test
