name: tests

on:
  push:
  schedule:
    - cron:  '0 2 * * *'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: |
        docker run -v $PWD:/data -w /data componolit/ci:gnat-community-2020 /bin/sh -c "apt-get update && apt-get install -y libz3-4 libz3-dev gcovr && make test"
